# Franka Arm Configuration (follower)
node_name: FrankaPanda
proxy_ip: 192.168.0.117
group: 224.0.0.1
group_port: 7720
group_name: DroidGroup

robot:
  - type: panda
    config_path: config/robot/droid_panda.yaml
grippers:
  - type: robotiq_gripper
    config_path: config/gripper/droid_robotiq.yaml
