# Gripper settings
gripper_pub_rate_hz: 100
gripper_command_rcvtimeo_ms: 500

# Gripper defaults
gripper_default_close_open_threshold: 0.01
gripper_default_speed_slow: 0.01
gripper_default_speed_fast: 20.0
gripper_default_force: 20.0