# Franka Arm Configuration (follower)
node_name: FrankaFollower
robot_ip: 10.10.10.202
proxy_ip: 141.3.53.63
group: 224.0.0.1
group_port: 7720
group_name: hardware_collection


arm_config_path: config/RobotArmConfig_follower.yaml
gripper_config_path: config/GripperConfig_follower.yaml
